#!/bin/sh
cat encoding.js utf8_fast.js hashing.js aes.js djson.js bn.js rsa.js | java -jar extra/yuicompress.jar --line-break 80 --verbose --type js >djcl.js
cat encoding.js hashing.js aes.js djson.js bn.js rsa.js | java -jar extra/yuicompress.jar --type js >djcl_ascii.js
